# Generated by Django 4.2.3 on 2023-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bg_color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
